# Ruff configuration for LLM Lab

# Target Python 3.8+
target-version = "py38"

# Line length
line-length = 120

# Exclude directories
exclude = [
    ".git",
    "__pycache__",
    "venv",
    ".venv",
    "build",
    "dist",
    "*.egg-info",
    ".pytest_cache",
    "htmlcov",
    ".ruff_cache",
    ".taskmaster",
    "datasets",
    "models",
]

[lint]
# Enable rules
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # pyflakes
    "I",    # isort
    "N",    # pep8-naming
    "UP",   # pyupgrade
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "DTZ",  # flake8-datetimez
    "T10",  # flake8-debugger
    "RUF",  # Ruff-specific rules
]

# Ignore specific rules
ignore = [
    "E203",  # whitespace before ':'
    "E501",  # line too long (handled by formatter)
    "B008",  # do not perform function calls in argument defaults
]

# Per-file ignores
[lint.per-file-ignores]
"tests/*" = ["S101", "B017"]  # Allow assert in tests
"__init__.py" = ["F401"]  # Allow unused imports in __init__ files

# Import configuration
[lint.isort]
known-first-party = ["config", "llm_providers", "evaluation", "benchmarks", "results_logger"]

# Formatter configuration
[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"