# Default configuration for Synthetic Data Generation Platform

generation:
  default_model: "gpt-4"
  temperature: 0.7
  max_tokens: 2048
  batch_size: 10
  retry_attempts: 3
  timeout: 30

validation:
  enable_quality_checks: true
  min_quality_score: 0.8
  check_diversity: true
  check_consistency: true
  check_format: true

privacy:
  enable_privacy_preservation: true
  differential_privacy_epsilon: 1.0
  anonymization_level: "medium"
  pii_detection: true
  pii_removal: true

domains:
  medical:
    templates_path: "templates/medical"
    validation_rules: "strict"
    privacy_level: "high"

  financial:
    templates_path: "templates/financial"
    validation_rules: "strict"
    privacy_level: "high"

  legal:
    templates_path: "templates/legal"
    validation_rules: "moderate"
    privacy_level: "medium"

  ecommerce:
    templates_path: "templates/ecommerce"
    validation_rules: "moderate"
    privacy_level: "low"

  educational:
    templates_path: "templates/educational"
    validation_rules: "moderate"
    privacy_level: "low"

  code:
    templates_path: "templates/code"
    validation_rules: "strict"
    privacy_level: "low"

output:
  default_format: "json"
  supported_formats: ["json", "csv", "parquet", "jsonl"]
  compression: false
  export_path: "exports/"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "synthetic_data.log"
