from setuptools import find_packages, setup

with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()

setup(
    name="llm-synthetic-data",
    version="0.1.0",
    author="LLM Lab Team",
    author_email="team@llm-lab.io",
    description="A comprehensive platform for generating high-quality synthetic data using LLMs",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/llm-lab/llm-lab",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
    ],
    python_requires=">=3.8",
    install_requires=[
        "transformers>=4.35.0",
        "datasets>=2.14.0",
        "pandas>=2.0.0",
        "numpy>=1.24.0",
        "scikit-learn>=1.3.0",
        "faker>=20.0.0",
        "pydantic>=2.0.0",
        "openai>=1.0.0",
        "anthropic>=0.8.0",
        "google-generativeai>=0.3.0",
        "tqdm>=4.65.0",
        "pyyaml>=6.0.1",
        "jinja2>=3.1.2",
        "jsonschema>=4.19.0",
        "python-dotenv>=1.0.0",
        "rich>=13.0.0",
        "click>=8.1.0",
        "fastapi>=0.104.0",
        "uvicorn>=0.24.0",
    ],
    extras_require={
        "dev": [
            "pytest>=7.4.0",
            "pytest-asyncio>=0.21.0",
            "pytest-cov>=4.1.0",
            "black>=23.0.0",
            "flake8>=6.0.0",
            "mypy>=1.5.0",
            "pre-commit>=3.4.0",
            "isort>=5.12.0",
        ],
        "privacy": [
            "differential-privacy>=0.2.0",
            "opacus>=1.4.0",
        ],
    },
    entry_points={
        "console_scripts": [
            "synth-data=synthetic_data.cli.main:main",
            "synth-generate=synthetic_data.cli.generate:generate",
            "synth-validate=synthetic_data.cli.validate:validate",
        ],
    },
    include_package_data=True,
    zip_safe=False,
)
